import type { Metadata } from 'next'
import Link from 'next/link'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://vexlo.co.uk'

export const metadata: Metadata = {
  title: 'Automated Google Reviews for UK Businesses | Vexlo',
  description:
    'Vexlo automatically requests Google reviews after every completed job and replies to every review — putting your reputation on autopilot. Get more 5-star reviews without lifting a finger.',
  keywords: [
    'automated Google reviews UK',
    'Google review automation for trades',
    'get more Google reviews automatically',
    'review request automation UK',
    'auto reply to Google reviews',
    'Google review software UK small business',
    'reputation management trades UK',
    'more 5 star reviews UK',
  ],
  alternates: { canonical: `${siteUrl}/google-reviews` },
  openGraph: {
    url: `${siteUrl}/google-reviews`,
    title: 'Automated Google Reviews — Vexlo',
    description:
      'Send automatic review requests after every job. Reply to every review automatically. Build a 5-star reputation on autopilot.',
    images: [{ url: `${siteUrl}/vexlo_logo.png`, width: 1200, height: 630, alt: 'Vexlo Google Review Automation' }],
  },
}

const painPoints = [
  "You finish a great job, the customer is happy — but you forget to ask for a review, and so does your customer.",
  "Your competitor has 80 reviews and keeps climbing Google. You have 12 reviews from 2 years ago and you're stuck on page 2.",
  "You've asked for reviews by hand, texted customers personally — it takes time you don't have and most still don't bother.",
  "Negative reviews sit unanswered on your profile, making you look unprofessional and driving potential customers away.",
  "Without a steady flow of recent reviews, Google's algorithm pushes you down in local search — even when your work is better.",
]

const howItWorks = [
  {
    step: 'Job is completed and marked done',
    detail:
      'When a job is completed — whether you mark it in your system or it triggers automatically — Vexlo knows it is time to ask for a review.',
  },
  {
    step: 'Automated SMS sent to the customer',
    detail:
      'Within minutes, your customer receives a personalised SMS thanking them for their business and asking them to share their experience on Google. One tap takes them straight to your review page.',
  },
  {
    step: 'Customer leaves a 5-star review',
    detail:
      'Because the message arrives at the perfect moment — while the job is still fresh — customers are far more likely to act. Our clients average 10–20 new reviews per month.',
  },
  {
    step: 'Vexlo automatically replies to every review',
    detail:
      'Every review — 5-star, 4-star, or the occasional complaint — gets a professional, personalised reply. Google rewards businesses that engage with reviews. You get the credit without the effort.',
  },
  {
    step: 'Your local search ranking improves',
    detail:
      'More recent reviews with consistent replies signals trust to Google. Your business climbs the local 3-pack, you get seen more, and more calls come in — all on autopilot.',
  },
]

const features = [
  {
    icon: '⭐',
    title: 'Automated Review Requests',
    description:
      'Triggered the moment a job completes. Personalised SMS with a direct link to your Google review page. No manual effort required — ever.',
  },
  {
    icon: '💬',
    title: 'Automated Review Replies',
    description:
      'Every review gets a thoughtful, on-brand reply. Positive reviews get thanked. Negative reviews get addressed professionally. Google rewards the engagement.',
  },
  {
    icon: '⏱️',
    title: 'Perfect Timing',
    description:
      'Reviews asked at the right moment convert at 30–40%. Sent while the memory is fresh — right after the job — not a week later when they have forgotten.',
  },
  {
    icon: '📈',
    title: 'Local Ranking Boost',
    description:
      'Google weighs review recency heavily. A steady flow of new reviews month after month consistently outperforms a business with lots of old reviews and nothing recent.',
  },
  {
    icon: '🔔',
    title: 'Negative Review Alerts',
    description:
      'If a customer leaves a 1 or 2-star review, you get an immediate alert so you can act fast — before it damages your reputation.',
  },
  {
    icon: '📊',
    title: 'Review Dashboard',
    description:
      'See every review request sent, every response received, and your rating trend over time — all in one place. Know exactly how your reputation is growing.',
  },
]

const stats = [
  { value: '93%', label: 'of customers say online reviews influence their buying decision' },
  { value: '10x', label: 'more reviews generated by automated requests vs asking manually' },
  { value: '40%', label: 'higher conversion when review request is sent within 1 hour of job completion' },
  { value: '#1', label: 'factor in Google local ranking is the quantity and recency of reviews' },
]

const faqs = [
  {
    q: 'How does Vexlo know when a job is complete?',
    a: 'Vexlo integrates with your booking or job management flow. When a job is marked as completed — either automatically or when you update it — the review request triggers. We set this up during onboarding.',
  },
  {
    q: 'Can I customise the review request message?',
    a: 'Yes. We write the message to match your brand voice, and you approve it before going live. It sounds personal to your business — not like a generic automated message.',
  },
  {
    q: 'What if a customer leaves a negative review?',
    a: 'You get an immediate alert. Vexlo can also draft an initial professional reply, giving you the chance to review and send. Responding quickly and professionally to negative reviews actually improves your overall reputation.',
  },
  {
    q: 'Do I need to change anything about how I currently work?',
    a: 'No. The system runs in the background. You continue working exactly as you do — Vexlo handles the review side automatically.',
  },
  {
    q: 'Is this against Google\'s policies?',
    a: 'Requesting reviews from genuine customers is fully compliant with Google\'s policies. What is not allowed is incentivising reviews or using fake reviews — Vexlo does neither. We simply make it easy for happy customers to leave the review they intended to leave anyway.',
  },
  {
    q: 'How quickly will I see results?',
    a: 'Most businesses see their first new reviews within the first week. Within 30 days you will typically have significantly more reviews than you had before — and Google\'s algorithm will start responding to that.',
  },
]

const relatedArticles = [
  {
    href: '/articles/google-reviews-recency-vs-quantity',
    tag: 'Reputation Management',
    title: 'Google Reviews: Why Recency Beats Quantity Every Time',
    excerpt: 'A business with 20 recent reviews will outrank one with 200 old reviews. Here is the data — and what to do about it.',
  },
  {
    href: '/articles/automated-google-review-requests-after-job',
    tag: 'How-To Guide',
    title: 'How to Automatically Request Google Reviews After Every Job',
    excerpt: 'Never forget to ask for a review again. How automated review requests build your ranking on autopilot.',
  },
  {
    href: '/articles/google-review-ranking-factors-explained',
    tag: 'SEO',
    title: 'Google Review Ranking Factors Explained: What Actually Moves the Needle',
    excerpt: 'Volume, recency, replies, keywords in reviews — here is exactly what Google weighs and how to optimise for each.',
  },
  {
    href: '/articles/how-to-get-more-google-reviews-trades',
    tag: 'Reputation Management',
    title: 'How to Get More Google Reviews as a Tradesperson (Without Begging)',
    excerpt: 'Practical, proven tactics for getting a steady stream of 5-star reviews — without awkward conversations or chasing customers.',
  },
]

export default function GoogleReviewsPage() {
  return (
    <div style={{ background: '#0a0a0a' }}>

      {/* HERO */}
      <section
        className="relative pt-36 pb-24 px-6 md:px-10 overflow-hidden"
        style={{ background: '#0a0a0a' }}
      >
        <div
          className="pointer-events-none absolute"
          style={{
            width: '600px', height: '600px',
            background: 'radial-gradient(circle, rgba(217,119,6,0.1) 0%, transparent 70%)',
            top: '-100px', right: '-100px',
          }}
        />
        <div className="max-w-6xl mx-auto relative z-10">
          <div className="max-w-3xl">
            <div
              className="inline-flex items-center gap-2 mb-6 px-3.5 py-1.5 rounded-full text-xs font-bold tracking-widest uppercase"
              style={{ background: 'rgba(217,119,6,0.12)', border: '1px solid rgba(217,119,6,0.3)', color: '#d97706' }}
            >
              <span>⭐</span> Google Review Automation
            </div>
            <h1
              className="font-display text-white mb-6 leading-none"
              style={{ fontSize: 'clamp(3rem, 5.5vw, 5.5rem)', letterSpacing: '0.02em' }}
            >
              Your work earns 5 stars.<br />
              <span className="font-serif" style={{ color: '#d97706', fontStyle: 'italic' }}>Let Vexlo collect them.</span>
            </h1>
            <p className="text-lg leading-relaxed mb-10" style={{ color: '#888', maxWidth: '560px' }}>
              Vexlo automatically sends a review request after every completed job and replies to every review on your behalf — building your Google reputation 24/7 without any manual effort.
            </p>
            <div className="flex flex-wrap gap-3 mb-12">
              <Link
                href="/enquiry"
                className="inline-flex items-center px-8 py-4 rounded text-sm font-bold tracking-wide text-white transition-all duration-200 hover:brightness-110 hover:-translate-y-px"
                style={{ background: '#d97706' }}
              >
                Start Getting Reviews →
              </Link>
              <Link
                href="#how-it-works"
                className="inline-flex items-center px-8 py-4 rounded text-sm font-semibold transition-all duration-200 hover:text-white"
                style={{ border: '1px solid #2a2a2a', color: '#e8e8e8' }}
              >
                See How It Works
              </Link>
            </div>

            {/* Mini stats row */}
            <div className="flex flex-wrap gap-8">
              {[
                { value: '10–20', label: 'new reviews/month average' },
                { value: '4 sec', label: 'to trigger after job done' },
                { value: '24/7', label: 'replies — never miss one' },
              ].map((s, i) => (
                <div key={i}>
                  <div className="font-display text-2xl" style={{ color: '#d97706', letterSpacing: '0.05em' }}>{s.value}</div>
                  <div className="text-xs mt-0.5" style={{ color: '#888' }}>{s.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* PAIN POINTS */}
      <section style={{ background: '#111111', padding: '80px 40px' }}>
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <div className="section-tag" style={{ textAlign: 'center' }}>The Problem</div>
            <h2
              className="font-display text-white mt-2"
              style={{ fontSize: 'clamp(2rem, 3.5vw, 3rem)', lineHeight: 1.05, letterSpacing: '0.02em' }}
            >
              Great work. Not enough reviews. <br />Your competitor is winning by default.
            </h2>
          </div>
          <div className="flex flex-col gap-3">
            {painPoints.map((pain, i) => (
              <div
                key={i}
                className="flex items-start gap-4 p-5 rounded-xl"
                style={{ background: 'rgba(239,68,68,0.05)', border: '1px solid rgba(239,68,68,0.15)' }}
              >
                <div
                  className="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold mt-0.5"
                  style={{ background: 'rgba(239,68,68,0.15)', color: '#ef4444' }}
                >
                  ✕
                </div>
                <p className="text-sm leading-relaxed" style={{ color: '#e8e8e8' }}>{pain}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* STATS BANNER */}
      <section style={{ background: '#d97706', padding: '60px 40px' }}>
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {stats.map((s, i) => (
              <div key={i}>
                <div className="font-display text-white mb-2" style={{ fontSize: 'clamp(2rem, 3.5vw, 3rem)', lineHeight: 1 }}>{s.value}</div>
                <div className="text-sm leading-snug" style={{ color: 'rgba(255,255,255,0.8)' }}>{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="how-it-works" style={{ background: '#0a0a0a', padding: '80px 40px' }}>
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <div className="section-tag" style={{ textAlign: 'center' }}>How It Works</div>
            <h2
              className="font-display text-white mt-2"
              style={{ fontSize: 'clamp(2rem, 3.5vw, 3rem)', lineHeight: 1, letterSpacing: '0.02em' }}
            >
              From completed job to published review — automatically.
            </h2>
          </div>
          <div className="relative">
            <div className="absolute left-8 top-0 bottom-0 w-px hidden md:block" style={{ background: '#2a2a2a' }} />
            <div className="flex flex-col gap-10">
              {howItWorks.map((item, i) => (
                <div key={i} className="relative flex flex-col md:flex-row gap-6 md:items-start">
                  <div
                    className="flex-shrink-0 w-16 h-16 rounded-full flex items-center justify-center font-display text-xl z-10 mx-auto md:mx-0"
                    style={{ background: '#111111', border: '2px solid #2a2a2a', color: '#d97706' }}
                  >
                    {i + 1}
                  </div>
                  <div className="flex-1 p-6 rounded-xl" style={{ background: '#111111', border: '1px solid #2a2a2a' }}>
                    <h3 className="font-bold text-sm mb-2" style={{ color: '#fff' }}>{item.step}</h3>
                    <p className="text-sm leading-relaxed" style={{ color: '#888' }}>{item.detail}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section style={{ background: '#111111', padding: '80px 40px' }}>
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <div className="section-tag" style={{ textAlign: 'center' }}>Everything Included</div>
            <h2
              className="font-display text-white mt-2"
              style={{ fontSize: 'clamp(2rem, 3.5vw, 3rem)', lineHeight: 1, letterSpacing: '0.02em' }}
            >
              Your reputation, managed on autopilot.
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {features.map((f, i) => (
              <div
                key={i}
                className="p-7 rounded-xl"
                style={{ background: '#1a1a1a', border: '1px solid #2a2a2a' }}
              >
                <div className="text-3xl mb-4">{f.icon}</div>
                <h3 className="font-bold text-sm mb-2" style={{ color: '#fff' }}>{f.title}</h3>
                <p className="text-sm leading-relaxed" style={{ color: '#888' }}>{f.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* IMPACT */}
      <section style={{ background: '#0a0a0a', padding: '80px 40px' }}>
        <div className="max-w-4xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
            <div>
              <div className="section-tag">The Business Impact</div>
              <h2
                className="font-display text-white mt-2 mb-6"
                style={{ fontSize: 'clamp(2rem, 3.5vw, 3rem)', lineHeight: 1.05, letterSpacing: '0.02em' }}
              >
                More reviews means more customers. It really is that simple.
              </h2>
              <p className="text-sm leading-relaxed mb-6" style={{ color: '#888' }}>
                Google uses review signals as one of its primary local ranking factors. Businesses that consistently generate new reviews rank higher in the local 3-pack — the three business listings that appear above organic search results.
              </p>
              <p className="text-sm leading-relaxed mb-8" style={{ color: '#888' }}>
                When a potential customer is searching for your service locally, appearing in those top three positions is worth more than any paid ad. And the businesses that occupy those spots are almost always the ones with the most recent, most consistent review activity.
              </p>
              <Link
                href="/articles/google-review-ranking-factors-explained"
                className="text-sm font-bold"
                style={{ color: '#d97706' }}
              >
                Read: What really drives Google review rankings →
              </Link>
            </div>
            <div className="flex flex-col gap-4">
              {[
                { pct: '76%', text: 'of local searches result in a visit to a business within 24 hours' },
                { pct: '89%', text: 'of consumers are likely to use a business that responds to all its reviews' },
                { pct: '3.3★', text: 'is the minimum star rating consumers say they need to consider a business' },
              ].map((s, i) => (
                <div
                  key={i}
                  className="p-6 rounded-xl flex items-start gap-5"
                  style={{ background: '#111111', border: '1px solid #2a2a2a' }}
                >
                  <div className="font-display flex-shrink-0" style={{ fontSize: '2rem', color: '#d97706', lineHeight: 1 }}>{s.pct}</div>
                  <p className="text-sm leading-relaxed" style={{ color: '#888' }}>{s.text}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section style={{ background: '#0a0a0a', padding: '80px 40px' }}>
        <div className="max-w-3xl mx-auto">
          <h2
            className="font-display text-white text-center mb-12"
            style={{ fontSize: 'clamp(2rem, 3.5vw, 3rem)', lineHeight: 1, letterSpacing: '0.02em' }}
          >
            Common questions.
          </h2>
          <div className="flex flex-col gap-4">
            {faqs.map((item, i) => (
              <div key={i} className="p-6 rounded-xl" style={{ background: '#111111', border: '1px solid #2a2a2a' }}>
                <h3 className="font-bold text-sm mb-2" style={{ color: '#fff' }}>{item.q}</h3>
                <p className="text-sm leading-relaxed" style={{ color: '#888' }}>{item.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* RELATED ARTICLES */}
      <section style={{ background: '#111111', padding: '80px 40px' }}>
        <div className="max-w-6xl mx-auto">
          <div className="section-tag">Learn More</div>
          <h2
            className="font-display text-white mb-10 mt-2"
            style={{ fontSize: 'clamp(1.8rem, 3vw, 2.5rem)', lineHeight: 1, letterSpacing: '0.02em' }}
          >
            Guides on Google reviews and reputation.
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
            {relatedArticles.map((article) => (
              <Link
                key={article.href}
                href={article.href}
                className="block p-6 rounded-xl transition-all duration-200 hover:-translate-y-0.5"
                style={{ background: '#1a1a1a', border: '1px solid #2a2a2a', textDecoration: 'none' }}
              >
                <span
                  className="text-xs font-bold px-2.5 py-1 rounded-full inline-block mb-4"
                  style={{ background: 'rgba(217,119,6,0.15)', color: '#d97706' }}
                >
                  {article.tag}
                </span>
                <h3 className="font-bold text-sm leading-snug mb-3" style={{ color: '#fff' }}>
                  {article.title}
                </h3>
                <p className="text-xs leading-relaxed mb-4" style={{ color: '#888' }}>
                  {article.excerpt}
                </p>
                <span className="text-xs font-bold" style={{ color: '#d97706' }}>Read article →</span>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ALSO SEE */}
      <section style={{ background: '#0a0a0a', padding: '40px 40px' }}>
        <div className="max-w-6xl mx-auto flex flex-wrap gap-4 items-center">
          <span className="text-sm" style={{ color: '#888' }}>Also part of Vexlo:</span>
          <Link href="/listings" className="text-sm font-bold transition-colors hover:text-white" style={{ color: '#d97706' }}>
            Business Listings Management →
          </Link>
        </div>
      </section>

      {/* CTA */}
      <section
        className="relative overflow-hidden text-center"
        style={{ background: '#111111', padding: '100px 40px' }}
      >
        <div
          className="pointer-events-none absolute inset-0"
          style={{ background: 'radial-gradient(ellipse at center, rgba(217,119,6,0.07) 0%, transparent 70%)' }}
        />
        <div className="max-w-2xl mx-auto relative z-10">
          <h2
            className="font-display text-white mb-4"
            style={{ fontSize: 'clamp(2.5rem, 4vw, 4.5rem)', lineHeight: 1, letterSpacing: '0.02em' }}
          >
            Ready to build a{' '}
            <span className="font-serif" style={{ color: '#d97706', fontStyle: 'italic' }}>5-star reputation?</span>
          </h2>
          <p className="mb-10 text-base" style={{ color: '#888', maxWidth: '460px', margin: '0 auto 40px' }}>
            Book a free demo and we will show you how Vexlo turns your completed jobs into a steady stream of Google reviews — without any extra work from you.
          </p>
          <Link
            href="/enquiry"
            className="inline-flex items-center px-9 py-4 rounded text-sm font-bold tracking-wide text-white transition-all duration-200 hover:brightness-110 hover:-translate-y-px"
            style={{ background: '#d97706' }}
          >
            Book Your Free Demo →
          </Link>
          <p className="mt-5 text-xs" style={{ color: '#888' }}>
            First month free. No setup fees. Live in 48 hours.
          </p>
        </div>
      </section>

      {/* Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Service',
            name: 'Automated Google Review Management',
            provider: { '@type': 'Organization', name: 'Vexlo', url: siteUrl },
            description:
              'Vexlo automatically requests Google reviews after every completed job and replies to all reviews on behalf of UK businesses.',
            areaServed: { '@type': 'Country', name: 'United Kingdom' },
            url: `${siteUrl}/google-reviews`,
          }),
        }}
      />
    </div>
  )
}
